### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevendreed** [stevendreed/prework-study-guide#2]
# CSS

## user story
```
As a new bootcamp student, I want pre-work notes structured on a webpage
to make finding information easier
```

## acceptance criteria
```
GIVEN > pre-work study guide website
WHEN  > I view the study guide
THEN  > I see dark blue header, footer, + four (4) boxes with a shadow
```

**Comment by palve-vaishnav** [comment]
for coloring header and footer you can use
   background-color:blue;  

and for shadow use
  box-shadow: 5px 5px 5px #000000;

**Comment by stevendreed** [comment]
@palve-vaishnav great advice, thank you!

**Comment by stevendreed** [comment]
- CSS style sheet added
- header, footer, and four boxes added
- shadow implemented
